### ISSUE TITLE
Firefox Support

### ISSUE THREAD

**Issue by Two-Tone** [EvergreenPotato/FairSteam#1]
It'd be great if the plug-in was ported to Firefox.

I should add that I do know that you mentioned on /r/pcgaming that it's high priority, just wanted to make an issue so that this can be tracked and eventually marked as "solved".

**Comment by EvergreenPotato** [comment]
http://www.arewewebextensionsyet.com/#
As far as I understand in a month Firefox 46 will be released. From this version we can easily port chrome extension to FF. I'll play with this solution.

**Comment by EvergreenPotato** [comment]
Firefox version is up and running. 
Github for for it: https://github.com/EvergreenPotato/FairSteam_Firefox
Firefox add-ons page: https://addons.mozilla.org/en-US/firefox/addon/fairsteam/
